[package]
name = "flv-cli"
version = "0.1.0"
edition = "2018"
authors =["Shell asypost@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flv-parser = {path="../flv-parser"}
clap = "2.33"